[package]
name = "xvmath"
version = "0.1.0"
authors = ["atil"]
edition = "2018"
description = "simd vector math library"
license = "idk how to license"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "0.1.18"

[lib]
name = "xvmath"
